### ISSUE TITLE
Requester Completion Descriptor Format in Xilinx Ultrascale does not reconstructs lower_address to 12bits

### ISSUE THREAD

**Issue by dramoz** [alexforencich/cocotbext-pcie#11]
Hello.

At [line 388 of rc.py](https://github.com/alexforencich/cocotbext-pcie/blob/master/cocotbext/pcie/core/rc.py#L388)

`cpl.lower_address = addr & 0x7f`

the mask of the lower address should be 0xfff (12bits) - or am I missing something?

Could you check?

Thanks,
Danilo.

**Comment by alexforencich** [comment]
The lower address field in the standard PCIe TLP is 7 bits, so the mask is correct.

However, the Xilinx ultrascale descriptor format has a 12 bit field as the hard IP core reconstructs the additional bits. This is currently not implemented in the hard IP core models in this repo, hence the field is truncated. Perhaps it's time to revisit that, there may be a simple way to reconstruct that from the bytes remaining field coupled with storing the original request.

**Comment by dramoz** [comment]
Thanks for the explanation. I changed the Issue title to something more appropriate

**Comment by alexforencich** [comment]
Just pushed some changes to the PCIe hard IP core models that should improve this.  Try it out and let me know how it works for you.

**Comment by dramoz** [comment]
Working fine. I also tested request completed and is working too.
Thanks!
