### ISSUE TITLE
configuration space decode in bytes vs dwords

### ISSUE THREAD

**Issue by typingArtist** [alexforencich/cocotbext-pcie#13]
https://github.com/alexforencich/cocotbext-pcie/blob/ed16549d05d13f6e2f7d5b6079db7b570f13dfb6/cocotbext/pcie/core/function.py#L252

That should perhaps read:
```python
elif 16 <= reg < 64:
```
similarly, the extended configuration space decode

https://github.com/alexforencich/cocotbext-pcie/blob/ed16549d05d13f6e2f7d5b6079db7b570f13dfb6/cocotbext/pcie/core/function.py#L255

should rather be
```python
elif 64 <= reg < 1024:
```

The same applies to the decoding in `write_config_register`.

**Comment by alexforencich** [comment]
Whoops, nice catch.  Just pushed that change, and I will probably cut a new release soon.
